(function(){const f="cart",g="wishlist";function u(){try{return JSON.parse(localStorage.getItem(f))||[]}catch{return[]}}function l(){try{return JSON.parse(localStorage.getItem(g))||[]}catch{return[]}}function w(t){localStorage.setItem(g,JSON.stringify(t))}function m(){const e=u().reduce((n,o)=>n+(o.quantity||1),0);document.querySelectorAll(".cart-icon span, #cart-count").forEach(n=>{n.innerText=e<10?"0"+e:String(e)})}function h(){const t=l();let e=document.getElementById("zaura-wish-badge");const n=document.getElementById("wishlist-icon");n&&(e||(e=document.createElement("span"),e.id="zaura-wish-badge",e.className="zaura-badge",n.appendChild(e)),e.innerText=t.length<10?"0"+t.length:String(t.length),e.style.display=t.length?"":"none")}function p(){document.querySelectorAll(".product-card, article.product-card").forEach(t=>{const e=t.querySelector("img");if(!e)return;const n=window.ZAURA_getProductIdFromSrc(e.getAttribute("src"));if(!n)return;t.setAttribute("data-product-id",n);const o="product.html?id="+encodeURIComponent(n),r=t.querySelector("a[href]");r&&(r.getAttribute("href")===""||r.getAttribute("href")==="#")&&r.setAttribute("href",o),e.closest("a")||(e.style.cursor="pointer",e.addEventListener("click",s=>{s.target.closest(".size-btn, .wishlist, button")||(window.location.href=o)}));const a=t.querySelector(".product-info");if(a&&!a.querySelector(".zaura-view-details")){const s=document.createElement("a");s.className="zaura-view-details",s.href=o,s.textContent="View details \u2192",a.appendChild(s)}const c=t.querySelector(".wishlist");if(c){const s=()=>{const d=l();c.classList.toggle("active",d.includes(n))};s(),c.style.cursor="pointer",c.addEventListener("click",d=>{d.stopPropagation();let i=l();i=i.includes(n)?i.filter(v=>v!==n):i.concat([n]),w(i),s(),h()})}})}function y(){const t=document.getElementById("wishlist-icon");t&&t.setAttribute("href","wishlist.html")}function b(){const t=document.getElementById("searchModal");if(!t)return;const e=t.querySelector(".modal-body");if(!e)return;e.innerHTML=`
      <input type="text" id="zauraSearchInput" class="form-control mb-3" placeholder="Search products, categories, fabric...">
      <div id="zauraSearchResults" class="zaura-search-results"></div>
    `;const n=document.getElementById("zauraSearchInput"),o=document.getElementById("zauraSearchResults"),r=Object.values(window.ZAURA_PRODUCTS||{});function a(c){const s=(c||"").trim().toLowerCase(),d=s?r.filter(i=>i.name.toLowerCase().includes(s)||i.category.toLowerCase().includes(s)||i.fabric&&i.fabric.toLowerCase().includes(s)):r.slice(0,6);if(!d.length){o.innerHTML=`<p class="text-muted small mb-0">No products match "${c}"</p>`;return}o.innerHTML=d.map(i=>`
        <a class="zaura-search-item" href="product.html?id=${encodeURIComponent(i.id)}">
          <img src="${i.image}" alt="" loading="lazy" decoding="async">
          <div>
            <div class="zsi-name">${i.name}</div>
            <div class="zsi-meta">${i.category} \xB7 Rs.${i.price.toFixed(2)}</div>
          </div>
        </a>`).join("")}n.addEventListener("input",c=>a(c.target.value)),t.addEventListener("shown.bs.modal",()=>{n.focus(),a("")}),a("")}document.addEventListener("DOMContentLoaded",()=>{p(),y(),b(),m(),h(),S()});function S(){const t=document.querySelectorAll(".navbar .nav-item.dropdown > a.dropdown-toggle");if(!t.length)return;function e(){const o=window.innerWidth>=992;t.forEach(r=>{if(o){r.removeAttribute("data-bs-toggle");const a=r.parentElement.querySelector(".dropdown-menu");a&&a.classList.remove("show"),r.parentElement.classList.remove("show"),r.setAttribute("aria-expanded","false")}else r.setAttribute("data-bs-toggle","dropdown")})}e();let n;window.addEventListener("resize",()=>{clearTimeout(n),n=setTimeout(e,120)}),document.querySelectorAll(".navbar .dropdown-menu .dropdown-item").forEach(o=>{o.addEventListener("click",()=>{if(window.innerWidth<992){const r=document.getElementById("navbarContent");r&&r.classList.contains("show")&&window.bootstrap&&window.bootstrap.Collapse.getOrCreateInstance(r).hide()}})})}window.ZAURA={getCart:u,getWish:l,setWish:w,updateCartBadge:m,updateWishBadge:h,addToCart(t){const e=u(),n=e.find(o=>o.id===t.id&&o.size===t.size&&o.color===t.color);n?n.quantity=(n.quantity||1)+(t.quantity||1):e.push(Object.assign({quantity:1},t)),localStorage.setItem(f,JSON.stringify(e)),m()}}})();
document.addEventListener("click",function(e){var t=e.target.closest(".navbar-nav .dropdown-toggle");if(!t)return;var noHover=window.matchMedia("(hover: none)").matches||window.innerWidth<992;if(!noHover)return;var li=t.parentElement,menu=li.querySelector(".dropdown-menu");if(!menu)return;if(!menu.classList.contains("show")){e.preventDefault();document.querySelectorAll(".navbar-nav .dropdown-menu.show").forEach(function(m){m.classList.remove("show")});menu.classList.add("show");t.setAttribute("aria-expanded","true")}});
